---
- name: Install Required Packages
  apt:
    name:
      - apache2 
      - mariadb-server 
      - libapache2-mod-php7.3
      - php-apcu
      - php7.3-gd
      - php7.3-json
      - php7.3-mysql
      - php7.3-curl
      - php7.3-mbstring
      - php7.3-intl
      - php-imagick 
      - php7.3-xml
      - php7.3-zip
      - php7.3-bz2
      - php7.3-ldap
      - php7.3-imap
      - php7.3-bcmath
      - php7.3-gmp
    state: latest

- name: Set PHP memory limit
  lineinfile:
    path: /etc/php/7.3/apache2/php.ini
    regex: "memory_limit ="
    line: "memory_limit = 1024M"

- name: Download Nextcloud install
  get_url:
    url: "https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.tar.bz2"
    dest: "/tmp/nextcloud-{{ nextcloud_version }}.tar.bz2"

- name: Extract Files
  unarchive:
    src: "/tmp/nextcloud-{{ nextcloud_version }}.tar.bz2"
    dest: "/var/www/html"
    owner: www-data
    group: www-data
    mode: 0750

- name: Ensure Apache php7.3 module is enabled
  apache2_module:
    name: php7.3
    state: present

- name: restart apache2
  systemd:
    name: apache2
    state: restarted

- name: Run Nextcloud Installer
  command: 
    chdir: /var/www/html/nextcloud
    cmd: "sudo -u www-data php occ  maintenance:install --database \"mysql\" --database-name \"nextcloud\"  --database-user \"{{ nextcloud_mysql_username }}\" --database-pass \"{{ nextcloud_mysql_password }}\" --admin-user \"{{ nextcloud_admin_username }}\" --admin-pass \"{{ nextcloud_admin_password }}\""

- name: Testing if NextCloud is available
  uri:
    url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}/nextcloud"
    return_content: true
  register: nextcloud_status

- name: NextCloud Web Info
  debug:
    msg: 
      - "You can access nextcloud at http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}/nextcloud"
      - "You will need the following information to setup Next Cloud:"
      - "Database Username: {{ nextcloud_mysql_username }}"
      - "Dataebase Password: {{ nextcloud_mysql_password }}"
      - "Database Name: nextcloud"
      - "Database Host: localhost"
  when: nextcloud_status.status == 200
