---
- name: Install Required Packages
  apt:
    name:
      - apache2 
      - mariadb-server 
      - libapache2-mod-php7.3
      - php-apcu
      - php7.3-gd
      - php7.3-json
      - php7.3-mysql
      - php7.3-curl
      - php7.3-mbstring
      - php7.3-intl
      - php-imagick 
      - php7.3-xml
      - php7.3-zip
      - php7.3-bz2
      - php7.3-ldap
      - php7.3-imap
      - php7.3-bcmath
      - php7.3-gmp
    state: latest

- name: Set PHP memory limit
  lineinfile:
    path: /etc/php/7.3/apache2/php.ini
    regex: "memory_limit ="
    line: "memory_limit = 1024M"

- name: Download Nextcloud install
  get_url:
    url: "https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.tar.bz2"
    dest: "/tmp/nextcloud-{{ nextcloud_version }}.tar.bz2"

- name: Extract Files
  unarchive:
    src: "/tmp/nextcloud-{{ nextcloud_version }}.tar.bz2"
    dest: "/var/www/html"
    owner: www-data
    group: www-data
    mode: 0750

- name: Install Redis Server
  apt:
    name:
      - redis-server
      - php-redis
    state: present

- name: Ensure Apache php7.3 module is enabled
  apache2_module:
    name: php7.3
    state: present

- name: Update apcu Config for cli
  lineinfile:
    path: /etc/php/7.3/cli/conf.d/20-apcu.ini
    line: "apc.enable_cli=1"

- name: restart apache2
  systemd:
    name: apache2
    state: restarted

- name: Run Nextcloud Installer
  command: 
    chdir: /var/www/html/nextcloud
    cmd: "php occ  maintenance:install --database \"mysql\" --database-name \"nextcloud\"  --database-user \"{{ nextcloud_mysql_username }}\" --database-pass \"{{ nextcloud_mysql_password }}\" --admin-user \"{{ nextcloud_admin_username }}\" --admin-pass \"{{ nextcloud_admin_password }}\""
  become: true
  become_user: www-data

- name: Generate nextcloud config
  command:
    chdir: /var/www/html/nextcloud
    cmd: "{{ item }}"
  loop:
    - "sudo -u www-data php occ config:system:set allow_local_remote_servers --value=true"
    - "sudo -u www-data php occ config:system:set memcache.local --value='\\OC\\Memcache\\Redis'"
    - "sudo -u www-data php occ config:system:set redis host --value=localhost"
    - "sudo -u www-data php occ config:system:set redis port --value=6379"
    - "sudo -u www-data php occ config:system:set trusted_domains 1 --value={{ (ansible_default_ipv4.network) | ipaddr('network') }}"
    - "sudo -u www-data php occ config:system:set trusted_domains 2 --value={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- name: Testing if NextCloud is available
  uri:
    url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}/nextcloud"
    return_content: true
  register: nextcloud_status

- name: NextCloud Web Info
  debug:
    msg: 
      - "You can access nextcloud at http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}/nextcloud"
      - "You will need the following information to setup Next Cloud:"
      - "NextCloud Admin Username: {{ nextcloud_admin_username }}"
      - "NextCloud Admin Password: {{ nextcloud_admin_password }}"
  when: nextcloud_status.status == 200
