---
- name: Copy createdb.sql
  template:
    src: createdb.sql.j2
    dest: /home/pi/createdb.sql
    owner: pi
    group: pi
    mode: 0744

- name: Create Database
  community.mysql.mysql_db:
    name: mattermost
    state: present

- name: load createdb.sql
  command: sudo mysql -u root < /home/pi/createdb.sql
