---
- name: Ensure Prerequisite Packages are installed
  apt:
    name:
      - lsb-release 
      - apt-transport-https 
      - ca-certificates
    state: latest

- name: Install Sury GPG Key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: Add Sury Repo
  apt_repository:
    repo: deb https://packages.sury.org/php/ buster main
    state: present

- name: Install php 7.4
  apt:
    name: php7.4
    state: latest
    update-cache: yes

