---
- name: Install postfix
  apt:
    name: 
      - postfix
      - libsasl2-modules
      - sasl2-bin
      - libsasl2-2
      - mailutils
    state: latest
    update-cache: yes

- name: Disable IPv6
  lineinfile:
    path: /etc/postfix/main.cf
    regex: "inet_protocols = all"
    line: "inet_protocols = ipv4"

- name: Set Postfix Domain
  lineinfile:
    path: /etc/postfix/main.cf
    regex: "myhostname ="
    line: "myhostname = {{ postfix_domain }}"

- name: Set Postfix Relay Server
  lineinfile:
    path: /etc/postfix/main.cf
    regex: "relayhost ="
    line: "relayhost = {{ postfix_relayhost }}"

- name: Configure gmail Authentication file
  template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    mode: 0600
    owner: root
    group: root
  when: postfix_use_gmail == true 

- name: Update Postfix Relay Server
  lineinfile:
    path: /etc/postfix/main.cf
    regex: "relayhost ="
    line: "relayhost = [smtp.gmail.com]:587"
  when: postfix_use_gmail == true 

- name: Enable tls
  lineinfile:
    path: /etc/postfix/main.cf
    regex: "smtp_use_tls ="
    line: "smtp_use_tls = yes"
  when: postfix_use_gmail == true 

- name: Enable SASL Auth
  lineinfile:
    path: /etc/postfix/main.cf
    regex: "smtp_sasl_auth_enable ="
    line: "smtp_sasl_auth_enable = yes"
  when: postfix_use_gmail == true

- name: Enable SASL Password Maps
  lineinfile:
    path: /etc/postfix/main.cf
    regex: "smtp_sasl_password_maps ="
    line: "smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd"
  when: postfix_use_gmail == true

- name: Set CA Certificate
  lineinfile:
    path: /etc/postfix/main.cf
    regex: "smtp_tls_CAfile ="
    line: "smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt"
  when: postfix_use_gmail == true

- name: Process Password file
  command: postmap /etc/postfix/sasl_passwd
  when: postfix_use_gmail == true

- name: Restart Postfix
  systemd:
    name: postfix
    state: restarted
