---
- name: apt-get update
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install MySQL Server
  apt:
    name: mariadb-server
    state: latest 
  when: ansible_facts['os_family'] == "Debian"
