---
- name: Create Service Account Group
  group:
    name: "mattermost"
    state: present

- name: Create Service Account User
  user:
    name: "mattermost"
    group: "mattermost"
    state: present
    
- name: Download Mattermost
  get_url:
    url: "https://github.com/SmartHoneybee/ubiquitous-memory/releases/download/v{{ mattermost_version }}/mattermost-v{{ mattermost_version }}-linux-arm.tar.gz"
    dest: "/tmp/mattermost-{{ mattermost_version }}-linux-arm.tar.gz"
    owner: pi
    group: pi
    mode: 0755

- name: Extract Install files
  unarchive:
    src: "/tmp/mattermost-{{ mattermost_version }}-linux-arm.tar.gz"
    dest: "/opt"
    owner: mattermost
    group: mattermost
    mode: g+w

- name: Create Data Directory
  file:
    path: /opt/mattermost/data
    state: directory
    owner: mattermost
    group: mattermost
    mode: g+w

- name: Update Mattermost config
  lineinfile:
    path: /opt/mattermost/config/config.json
    regex: '\"DriverName\"\: \"postgres\"\,'
    line: '    "DriverName": "mysql",'
    
- name: Update Mattermost config
  lineinfile:
    path: /opt/mattermost/config/config.json
    regex: '\"DataSource\"\:\ \"postgres\:\/\/mmuser\:mostest\@localhost\/mattermost_test\?sslmode\=disable\\u0026connect_timeout\=10\"\,'
    line: "    \"DataSource\": \"{{ mattermost_mysql_username }}:{{ mattermost_mysql_password }}@tcp(localhost:3306)/mattermost?charset=utf8mb4,utf8&writeTimeout=30s\","

- name: Creating systemd service
  copy:
    src: files/mattermost.service
    dest: /lib/systemd/system/mattermost.service
    mode: 0755
    owner: root
    group: root

- name: Enable Mattermost to run on boot and start
  systemd:
    name: mattermost
    state: started
    daemon_reload: yes
    enabled: yes

- name: Testing if mattermost is available
  uri:
    url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8065" 
    return_content: true
  register: mattermost_status

- name: Mattermost Web Info
  debug:
    msg: "You can access mattermost at http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8065"
  when: mattermost_status.status == 200
 
