---
- name: Preparing
  apt:
    name:
      - curl
      - apache2
    state: latest

- name: Download MeshChat
  get_url:
    url: "https://s3.amazonaws.com/aredn/meshchat_{{ meshchat_version }}_all.deb"
    dest: "/tmp/meshchat_{{ meshchat_version }}_all.deb"
    owner: root
    group: root
    mode: 0755

- name: Install MeshChat Package
  apt:
    deb: "/tmp/meshchat_{{ meshchat_version }}_all.deb"

- name: Setting MeshChat Zone
  lineinfile:
    path: /usr/lib/cgi-bin/meshchatconfig.pm
    regex: '\$pi_zone'
    line: "our $pi_zone = '{{ meshchat_zone }}'; "

- name: Setting MeshChat Node
  lineinfile:
    path: /usr/lib/cgi-bin/meshchatconfig.pm
    regex: '\$local_meshchat_node'
    line: "our $local_meshchat_node = '{{ meshchat_node }}'; "

- name: Ensuring apache2 is running
  systemd:
    name: apache2
    state: restarted

- name: checking if meshchat is running
  uri:
    url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}/meshchat"
    return_content: true
  register: meshchat_status

- name: Endpoint Details
  debug:
    msg: "You should now be able to access meshchat at http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}/meshchat"
  when: meshchat_status.status == 200

